#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
export IDEA_VM_OPTIONS=/opt/jetbra/vmoptions/idea.vmoptions
export JETBRAINS_CLIENT_VM_OPTIONS=/opt/jetbra/vmoptions/jetbrains_client.vmoptions
export PATH=$PATH:~/go/bin

picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/wallpapers/girl_bridge_wallpaper.jpg

$HOME/.config/polybar/launch.sh
flameshot &
discord &

setxkbmap "us,ru" ",winkeys" "grp:caps_toggle" &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 󰲠 󰲢 󰲤 󰲦 󰲨 󰲪

bspc config active_border_color '#5B8FB9'
bspc config normal_border_color '#393E6F'
bspc config focused_border_color '#5B8FB9'

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true